package codex

// Accessor is a type def of a function that returns an AttributeNode
type Accessor func(interface{}) *AttributeNode

// Returns the TableNode scoped to the Accessor
func (a Accessor) Table() *TableNode {
	return a("").Table
}

// Returns the name of the TableNode scoped to the Accessor
func (a Accessor) Name() string {
	return a("").Table.Name
}

// Returns a pointer to a SelectManager with the initial projections provided.
func (a Accessor) Select(projections ...interface{}) *SelectManager {
	return a.From(a.Table()).Select(projections...)
}

// Returns a pointer to a SelectManager with the initial filter provided.
func (a Accessor) Where(expr interface{}) *SelectManager {
	return a.From(a.Table()).Where(expr)
}

// Returns a pointer to a SelectManager with an initial InnerJoinNode.
func (a Accessor) InnerJoin(expr interface{}) *SelectManager {
	return a.From(a.Table()).InnerJoin(expr)
}

// Returns a pointer to a SelectManager with an initial OuterJoinNode.
func (a Accessor) OuterJoin(expr interface{}) *SelectManager {
	return a.From(a.Table()).OuterJoin(expr)
}

// Returns a pointer to a SelectManager with an initial Ordering.
func (a Accessor) Order(expr interface{}) *SelectManager {
	return a.From(a.Table()).Order(expr)
}

// Returns a pointer to a SelectManager with an initial Grouping.
func (a Accessor) Group(groupings ...interface{}) *SelectManager {
	return a.From(a.Table()).Group(groupings...)
}

// Returns a pointer to a SelectManager with an initial Having.
func (a Accessor) Having(expr interface{}) *SelectManager {
	return a.From(a.Table()).Having(expr)
}

// Returns a pointer to a SelectManager with for the given TableNode.
func (a Accessor) From(relation *TableNode) *SelectManager {
	return Selection(relation)
}

// Returns a pointer to a InsertManager with initial the values provided.
func (a Accessor) Insert(expr ...interface{}) *InsertManager {
	return Insertion(a.Table()).Insert(expr...)
}

// Returns a pointer to a UpdateManager with initial the columns provided.
func (a Accessor) Set(expr ...interface{}) *UpdateManager {
	return Modification(a.Table()).Set(expr...)
}

// Returns a pointer to a DeleteManager with the initial filter provided.
func (a Accessor) Delete(expr interface{}) *DeleteManager {
	return Deletion(a.Table()).Delete(expr)
}

// Returns string, error generated by calling ToSql on an SelectManager.
func (a Accessor) ToSql() (string, []interface{}, error) {
	return a.From(a.Table()).ToSql()
}
